### ISSUE TITLE
Syntax error for Entra-Cleanup-StaleDevices.ps1

### ISSUE THREAD

**Issue by Jones-Bones** [Mr-Tbone/Azure#1]
Maybe something changed in PS Graph module, but these 2 commands `Update-MgDevice -Id $device.Id -AccountEnabled $False` and `Remove-MgDevice -Id $device.Id` fail.

Should be:

`Update-MgDevice -DeviceId $device.Id -AccountEnabled:$False` and `Remove-MgDevice -DeviceId $device.Id` respectively

Both commands expect _Id_ property, but parameter is called _DeviceId_ by some reason and for Update-MgDevice, [AccountEnabled is a switch parameter](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1025).

Unrelated, but I have always disliked these MS Graph PS module commands. I would recommend abandoning them and using just Invoke-MgGraphRequest, e.g., to disable device `Invoke-MgGraphRequest -Uri 'https://graph.microsoft.com/v1.0/devices/{IdGoesHere}' -Method PATCH -Body @{'accountEnabled' = $true}`. [Associated Graph API call documentation](https://learn.microsoft.com/en-us/graph/api/device-update?view=graph-rest-1.0).

Pros:

- Better documentation / ability to search problems since you are using native API calls
- You can test calls in Graph Explorer
- More reliable. In the past I experienced unexpected behavior which pushed me to move to using native API calls
- Less PS modules installed, you only need _Microsoft.Graph.Authentication_

Cons:

- Worse at quick interactive tasks, more meant for scripting
- More difficult to understand at first

**Comment by Jones-Bones** [comment]
Oh, and there is some unneeded code in the end, probably left after some testing :)

```
$graphApiVersion = "beta"
$Resource = "devices"
$filter = "?`$filter=ApproximateLastSignInDateTime le $($deleteDate)"
$results=@()
$uri = "https://graph.microsoft.com////$graphApiVersion/$($Resource)$($filter)"
$result=Invoke-RestMethod -Uri $uri -Headers $MgGraphAccessToken -Method Get
$results+=$result
#disconnect-mggraph | out-null
```

**Comment by Mr-Tbone** [comment]
Thanks for the tip.
Yes I must have taken one of my test scripts instead of the final when publishing. Both commands are now fixed and the junk at the end is removed.
I usually use the MG commands when available, but they are not stable and sometimes they change. So I might need to re think this for future scripts.
